// Generated by scripts/build_routes.py; edit page templates and blog/index.json.
export const routeMap = {
  "/": {
    "page": "home",
    "source": "/index.html"
  },
  "/about": {
    "page": "about",
    "source": "/about.html"
  },
  "/philosophy": {
    "page": "philosophy",
    "source": "/philosophy.html"
  },
  "/blog": {
    "page": "blog",
    "source": "/blog.html"
  },
  "/roadmap": {
    "page": "roadmap",
    "source": "/roadmap.html"
  },
  "/blog/welcome-to-cabin": {
    "page": "blog",
    "source": "/blog/welcome-to-cabin/index.html"
  },
  "/blog/defining-cabin": {
    "page": "blog",
    "source": "/blog/defining-cabin/index.html"
  },
  "/blog/the-minimum-lovable-cabin": {
    "page": "blog",
    "source": "/blog/the-minimum-lovable-cabin/index.html"
  }
};
