"""Generate direct-entry documents for clean URLs on GitHub Pages."""
from pathlib import Path
import json, re, html
ROOT=Path(__file__).resolve().parents[1]
pages={'/':'index.html','/about':'about.html','/philosophy':'philosophy.html','/blog':'blog.html','/roadmap':'roadmap.html'}
routes={path:{'page':'home' if path=='/' else path[1:],'source':'/'+file} for path,file in pages.items()}
for path,file in pages.items():
    if path=='/': continue
    target=ROOT/path.lstrip('/')/'index.html'
    target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text((ROOT/file).read_text(encoding='utf-8'),encoding='utf-8')
manifest=json.loads((ROOT/'blog/index.json').read_text(encoding='utf-8'))
for post in manifest['posts']:
    slug=post.get('slug') or Path(post['path']).stem
    if not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*',slug):
        raise ValueError('Blog slugs must be lower-case, hyphen-separated words')
    path='/blog/'+slug
    source='/blog/'+slug+'/index.html'
    routes[path]={'page':'blog','source':source}
    text=(ROOT/'blog.html').read_text(encoding='utf-8')
    title=html.escape(post['title']);excerpt=html.escape(post.get('excerpt',''))
    text=re.sub(r'<title>.*?</title>','<title>'+title+' — Cabin Blog</title>',text)
    text=re.sub(r'<link rel="canonical"[^>]+>','<link rel="canonical" href="https://writecabin.com'+path+'">',text)
    text=re.sub(r'<meta name="description"[^>]+>','<meta name="description" content="'+excerpt+'">',text)
    text=re.sub(r'<meta property="og:title"[^>]+>','<meta property="og:title" content="'+title+' — Cabin Blog">',text)
    text=re.sub(r'<meta property="og:description"[^>]+>','<meta property="og:description" content="'+excerpt+'">',text)
    text=re.sub(r'<meta property="og:url"[^>]+>','<meta property="og:url" content="https://writecabin.com'+path+'">',text)
    text=re.sub(r'<main[\s\S]*?</main>','<main id="main"><article class="article-shell" data-article-mount><header><h1>'+title+'</h1><p>'+excerpt+'</p></header></article></main>',text)
    target=ROOT/source.lstrip('/');target.parent.mkdir(parents=True,exist_ok=True);target.write_text(text,encoding='utf-8')
(ROOT/'js/routes.js').write_text('// Generated by scripts/build_routes.py; edit page templates and blog/index.json.\nexport const routeMap = '+json.dumps(routes,indent=2)+';\n',encoding='utf-8')
(ROOT/'.nojekyll').touch()
print('Generated',len(routes),'clean route entries.')
